services:
  db:
    container_name: PhotoBotDB
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  bot:
    build: .
    container_name: PhotoBot
    command: python bot/main.py
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pg_data: